# Site settings
title: "Su-Don't"
email: shapero.daniel@gmail.com
description: Confessions of an inept mathematician
baseurl: ""
url: "http://danshapero.github.io"
github_username: danshapero

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]